# Site settings
email: 
baseurl: "/blog"
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Adam Brownell Blog
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Adam Brownell
profile_img: 
profile: 
social:
  github: https://github.com/adam1brownell

# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]
