# Site settings
email:
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics:

# SEO settings
title: Brownell Blog
description:
url: ""
twitter_username:
default_img:

# Profile settings
name: Adam Brownell
profile_img: https://thegraphicsfairy.com/wp-content/uploads/2015/08/Vintage-Buffalo-Silhouette-GraphicsFairy.jpg
profile: "Born in SoCal, living in West Hollywood. Studied Cognitive Science/Computation at UCLA. Data Scientist at Retina.ai. Love to surf, talk about the brain & robots."
social:
  github: https://github.com/adam1brownell
  linkedin: https://www.linkedin.com/in/adam-brownell-581a89b5/
  facebook: https://www.facebook.com/adam.brownell.3
  instagram: https://www.instagram.com/admbrwnll/


# Build settings
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap]
